import "./event";
import "./debug";
import "./flow";
import "./math";
import "./date";
import "./boolean";
import "./variable";
import "./function";
import "./string";
import "./http";
import "./webhook";
import "./odata";
import "./sftp";
import "./soap";
import "./auth";
import "./oauth2Saml";
import "./oauth2ClientCredentials";
import "./dropbox";
import "./facebook";
import "./azureStorage";
import "./awsDynamoDb";
import "./awsKinesis";
import "./mongo";
import "./struct";
import "./github";
import "./microsoft365";
import "./jira";
import "./google";
import "./array";
import "./set";
import "./map";
import "./reroute";
import "./xml";
import "./csv";
import "./code";
import "./crypto";
import "./slack";
import "./stripe";
import "./salesforce";
import "./workday";
import "./twilio";
import "./smtp";
import "./sap";
import "./linkedin";

let registered = false;

export function registerBuiltins(): void {
  if (registered) return;
  registered = true;
}
