import "@hermione/graph/nodes/event";
import "@hermione/graph/nodes/debug";
import "@hermione/graph/nodes/flow";
import "@hermione/graph/nodes/math";
import "@hermione/graph/nodes/date";
import "@hermione/graph/nodes/boolean";
import "@hermione/graph/nodes/variable";
import "@hermione/graph/nodes/function";
import "@hermione/graph/nodes/string";
import "@hermione/graph/nodes/http";
import "@hermione/graph/nodes/webhook";
import "@hermione/graph/nodes/odata";
import "@hermione/graph/nodes/sftp";
import "@hermione/graph/nodes/soap";
import "@hermione/graph/nodes/auth";
import "@hermione/graph/nodes/oauth2Saml";
import "@hermione/graph/nodes/oauth2ClientCredentials";
import "@hermione/graph/nodes/dropbox";
import "@hermione/graph/nodes/facebook";
import "@hermione/graph/nodes/azureStorage";
import "@hermione/graph/nodes/awsDynamoDb";
import "@hermione/graph/nodes/awsKinesis";
import "@hermione/graph/nodes/mongo";
import "@hermione/graph/nodes/struct";
import "@hermione/graph/nodes/github";
import "@hermione/graph/nodes/microsoft365";
import "@hermione/graph/nodes/jira";
import "@hermione/graph/nodes/google";
import "@hermione/graph/nodes/array";
import "@hermione/graph/nodes/set";
import "@hermione/graph/nodes/map";
import "@hermione/graph/nodes/reroute";
import "@hermione/graph/nodes/xml";
import "@hermione/graph/nodes/csv";
import "@hermione/graph/nodes/code";
import "@hermione/graph/nodes/crypto";
import "@hermione/graph/nodes/slack";
import "@hermione/graph/nodes/stripe";
import "@hermione/graph/nodes/salesforce";
import "@hermione/graph/nodes/workday";
import "@hermione/graph/nodes/twilio";
import "@hermione/graph/nodes/smtp";
import "@hermione/graph/nodes/sap";
import "@hermione/graph/nodes/linkedin";
import "@hermione/graph/nodes/sendgrid";
import "@hermione/graph/nodes/smartRecruiters";

let registered = false;

export function registerBuiltins(): void {
  if (registered) return;
  registered = true;
}
